# trndi-cli — LCL-free console front end for Trndi.
# Builds against the vendored trndi submodule (X_CONSOLE native + API layer).

T := vendor/trndi
FPC ?= fpc

# Extra flags from the environment, e.g. FPCEXTRA='-Fl/usr/local/lib' on BSD.
FPCEXTRA ?=

# Build identity for --version, generated into build/ before each compile.
# git describe names the release when one is tagged and falls back to the
# short SHA otherwise, so a shallow CI checkout without tags still says
# something useful; a tarball with no repository at all says "unknown".
VERSION_INC := build/cliversion.inc
CLI_DESC := $(shell git describe --tags --always --dirty 2>/dev/null || echo unknown)
TRNDI_DESC := $(shell git -C $(T) describe --tags --always 2>/dev/null || echo unknown)

UNITDIRS := -Fu$(T)/units/trndi -Fu$(T)/units/trndi/api \
            -Fu$(T)/units/slicke -Fu$(T)/units/misc
FPCFLAGS := -Mobjfpc -Sh -dX_CONSOLE -dWITHTHREADS $(UNITDIRS) -Fi$(T)/inc \
            -Fibuild -FUbuild -FEbin -otrndi-cli $(FPCEXTRA)

all: bin/trndi-cli

# Rewritten only when the description actually changed, so an unchanged
# working tree does not force a recompile on every make.
$(VERSION_INC): FORCE
	@mkdir -p build
	@printf '%s\n' \
	  '{ Generated by the build; not committed. Included inside a const' \
	  '  block, so it carries no const keyword of its own. }' \
	  "  CLI_VERSION = '$(CLI_DESC)';" \
	  "  CLI_TRNDI = '$(TRNDI_DESC)';" > $@.tmp
	@cmp -s $@.tmp $@ 2>/dev/null && rm -f $@.tmp || mv $@.tmp $@

FORCE:

bin/trndi-cli: src/trndicli.pp src/trndicli.settings.pp $(VERSION_INC) $(wildcard $(T)/units/trndi/*.pp $(T)/units/trndi/api/*.pp)
	@mkdir -p build bin
	$(FPC) $(FPCFLAGS) src/trndicli.pp

debug: src/trndicli.pp $(VERSION_INC)
	@mkdir -p build bin
	$(FPC) $(FPCFLAGS) -g -gl -gh src/trndicli.pp

clean:
	rm -rf build bin

# Haiku has no /usr/local: hand-built software lives under non-packaged, and
# the data directory is data/ rather than share/. Everywhere else the usual.
ifeq ($(shell uname -s),Haiku)
  PREFIX ?= /boot/home/config/non-packaged
  DATADIR ?= $(PREFIX)/data
else
  PREFIX ?= /usr/local
  DATADIR ?= $(PREFIX)/share
endif

# The binary into $(PREFIX)/bin and the shell completions where bash, zsh and
# fish look. Two steps rather than install -D: BSD install has no -D.
install: bin/trndi-cli install-completions
	install -d $(DESTDIR)$(PREFIX)/bin
	install -m 755 bin/trndi-cli $(DESTDIR)$(PREFIX)/bin/trndi-cli

install-completions:
	install -d $(DESTDIR)$(DATADIR)/bash-completion/completions
	install -m 644 completions/trndi-cli.bash $(DESTDIR)$(DATADIR)/bash-completion/completions/trndi-cli
	install -d $(DESTDIR)$(DATADIR)/zsh/site-functions
	install -m 644 completions/_trndi-cli $(DESTDIR)$(DATADIR)/zsh/site-functions/_trndi-cli
	install -d $(DESTDIR)$(DATADIR)/fish/vendor_completions.d
	install -m 644 completions/trndi-cli.fish $(DESTDIR)$(DATADIR)/fish/vendor_completions.d/trndi-cli.fish

# Remove what install put there. The share/ directories stay: they are the
# shells' own, not ours.
uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/trndi-cli
	rm -f $(DESTDIR)$(DATADIR)/bash-completion/completions/trndi-cli
	rm -f $(DESTDIR)$(DATADIR)/zsh/site-functions/_trndi-cli
	rm -f $(DESTDIR)$(DATADIR)/fish/vendor_completions.d/trndi-cli.fish

.PHONY: all debug clean install install-completions uninstall FORCE
